### ISSUE TITLE
Remove information about internal implementation from documentation

### ISSUE THREAD

**Issue by bablosoft** [CheshireCaat/BASRemote.NET#1]
Please remove or move to separate wiki topic description of internal implementation, like: FastExecuteScript.exe, websockets, etc.

Most of users just want to start using library and not interested in how it works internally.

```
This uses a portable version of the engine to execute the script (FastExecuteScript). Interaction with the script is based on the same principles as the web interface (via the WebSocket connection).
```
```
On disposing client closes WebSocket connection and terminate FastExecuteScript process.
```
->
```
On disposing client closes WebSocket connection and terminate BAS process.
```

```
StartAsync() method contains two main steps:

    Starting the engine service (Download, unzip and run executable)
    Starting the socket service (Connect to WebSocket and other)
```

Instead, please add information about BAS and where it can be downloaded from for users who are unfamiliar with software

**Comment by CheshireCaat** [comment]
I deleted some of internal information. Please check if i should remove something else.
