### ISSUE TITLE
help me show borwser 

### ISSUE THREAD

**Issue by lovelyn2210** [CheshireCaat/BASRemote.NET#12]
i can't find func show browser like in Bas.

**Comment by CheshireCaat** [comment]
Hello, @lovelyn2210

Look at the file with the source code for the web-interface API, there you can find all the requests you are interested in. You can find it here - [link](https://bablosoft.com/buildinterface/bas-api/bas-api.js). The library provides basic interaction with BAS scripts.

In your case you should send message like this:

```javascript
ShowBrowser(BrowserId)
{
    this.Send("show_browser", {"browser_id": BrowserId})
}
```

And for C # this way::
```csharp
client.Send("show_browser", new Params { 
    ["browser_id"] = yourBrowserId 
});
```

You can also write a custom function to solve your problem in order to don't repeat this code many times.

If I answered your question, please close this ticket.

**Comment by duynh91** [comment]
> ```cs
> client.Send("show_browser", new Params { 
>     ["browser_id"] = yourBrowserId 
> });
> ```

Dear @CheshireCaat 

With C#, I followed issue [no.12](https://github.com/CheshireCaat/BASRemote.NET/issues/12) to show the browser. However, the browser is not showed as expected :(
I tried to send the "show_browser" message in the RunFunction function but it didn't work either
> ```cs
> private void RunFunction(string functionName, Params functionParams, Action<dynamic> onResult, Action<Exception> onError) {
>    Id = Rand.NextInt(1, 1000000);
>   Client.Send("start_thread", new Params {{"thread_id", Id}});
>   Client.Send("show_browser", new Params {{ "browser_id", Id }});
>   ....
> ```
Very sorry, but thanks for supporting me.

Thank you!

**Comment by CheshireCaat** [comment]
Good day, @duynh91!

First of all, please, keep in mind the following points:
- Do not modify internal/private library methods unnecessarily.
- Thread id and browser id, I think, cannot be the same.
- Review [this](https://wiki.bablosoft.com/web-interface/#/inspectingbrowser) documentation properly.

You can retrieve real browser id using **browser_add** event. Based on web-interface docs this event `fired after new browser created. Custom interface must preserve browser id to get browser content later`. 

In addition you can show browser directly from your event handler, which may be convenient for you. You can also check `js` api sources, specifically **AddBrowser** method and where it is called from.

If it helps please close issue.

**Comment by bablosoft** [comment]
> However, the browser is not showed as expected :(
> I tried to send the "show_browser" message in the RunFunction function but it didn't work either

In order to interact with browser, please use BAS functions https://github.com/CheshireCaat/BASRemote.NET#running-custom-code

Solution which uses ```client.Send``` is a workaround, better to avoid it.

In case if you have any problems, please attach full source.

**Comment by duynh91** [comment]
Dear @bablosoft & @CheshireCaat ,
I will follow that.

Thanks for your support!!
