### ISSUE TITLE
[WinError 2] Не удается найти указанный файл

### ISSUE THREAD

**Issue by dol8it** [CheshireCaat/BASRemote.NET#13]
Делаю все по гайду, проверил 100 раз правильность. Вываливает ошибку:
[WinError 2] Не удается найти указанный файл

Как решить? Или либа на том свете уже?

Скриншот ошибки:
![image](https://user-images.githubusercontent.com/60980006/106261385-8b4e8d80-6232-11eb-9567-0f5f42f4084d.png)

**Comment by bablosoft** [comment]
This issue is not related to BASRemote.NET.
