### ISSUE TITLE
Bas не возвращает в c#

### ISSUE THREAD

**Issue by dol8it** [CheshireCaat/BASRemote.NET#14]
В общем целый день проверял, ретюрн не останавливает функцию на шарпе и когда доходит до того самого ретюрна, просто работает дальше, уже ничего не выполняя.
Делал success перед return - функцию возвращало, но без данных пустую. Делаю success после return - застряет и зависает. Что делать?

**Comment by bablosoft** [comment]
Hi, in order to submit a ticket please follow these rules:

* Attach source code. Сode size should be as small as possible. In other words, it should only demonstrate the problem and nothing else.
* Describe steps to reproduce the problem.
* Describe actual and expected results.
