### ISSUE TITLE
Script engine not supported (Required 22.4.2 or newer)

### ISSUE THREAD

**Issue by willowTank** [CheshireCaat/BASRemote.NET#15]
I am getting error when I try to run sample project.

![image](https://user-images.githubusercontent.com/24641385/146525326-4725fe83-86d1-44b6-a0c3-8972ff4f4295.png)

**Comment by bablosoft** [comment]
Can't reproduce, sample code works as expected. Please attach code which reproduces the problem.

**Comment by bablosoft** [comment]
Closed because no information.
