### ISSUE TITLE
Add information to users who are unfamiliar with BAS.

### ISSUE THREAD

**Issue by bablosoft** [CheshireCaat/BASRemote.NET#4]
Need to add information on what is BAS, where it can be downloaded, that current library interacts with BAS by running functions, small description on what is BAS functions and how it can be created on main page.

User which is new to BAS must have understanding on how to start using library by reading main page.

**Comment by CheshireCaat** [comment]
Check out the updated README, please.

**Comment by bablosoft** [comment]
Thanks, that's better, I'll some things by myself later.
