### ISSUE TITLE
Throw error if BAS can't start script.

### ISSUE THREAD

**Issue by bablosoft** [CheshireCaat/BASRemote.NET#7]
In case if BAS can't start script, it sends following message 
```
{"async":false,"data":{"text":"Error from server : Wrong credentials"},"id":0,"type":"message"}
```

Current implementation freezes forever after calling 
```
await Client.StartAsync();
```

1) This method should never freeze, after timeout it must throw timeout exception.
2) If BAS sends response with error, following error must be thrown by library.

**Comment by CheshireCaat** [comment]
> This method should never freeze, after timeout it must throw timeout exception.

Does this mean that I need to add support for canceling a task after launch?

**Comment by CheshireCaat** [comment]
Check the latest update. If all is ok, i will close the issue.

**Comment by bablosoft** [comment]
> Does this mean that I need to add support for canceling a task after launch?

I mean, that if FastExecuteScript.exe have been started and there is no thread_start message for 60 seconds, it is required to throw exception. Is this implemented after fix?

**Comment by CheshireCaat** [comment]
> I mean, that if FastExecuteScript.exe have been started and there is no thread_start message for 60 seconds, it is required to throw exception. Is this implemented after fix?

No, more precisely, now it can be done, but not as you described. The fix contains an authentication error handler. If an error occurs, the task will be stopped with an error. And now you can pass the cancellation token to the Start method. For example, you can just use this [CancelAfter](https://docs.microsoft.com/ru-ru/dotnet/api/system.threading.cancellationtokensource.cancelafter?view=netframework-4.8) and pass as argument any timeout for client initialization.

**Comment by bablosoft** [comment]
> No, more precisely, now it can be done, but not as you described.

Can you paste code with example?

**Comment by CheshireCaat** [comment]
> Can you paste code with example?

```csharp
using (var client = new BasRemoteClient(new Options {ScriptName = "RemoteControlTest"}))
{
        var cts = new CancellationTokenSource();
        cts.CancelAfter(TimeSpan.FromSeconds(60));

        await client.Start(cts.Token);
        Console.ReadKey();
}
```

But you need to keep in mind that the specified timeout may pass earlier if the engine starts for a long time.

**Comment by bablosoft** [comment]
> But you need to keep in mind that the specified timeout may pass earlier if the engine starts for a long time.

Specified timeout can fire while installing a new BAS version. Is there no way to use it without any additional code and run it only after processes start?

**Comment by CheshireCaat** [comment]
> Specified timeout can fire while installing a new BAS version. Is there no way to use it without any additional code and run it only after processes start?

I meant that the timeout will not affect the launch of the engine and socket. Look at this part of code:
https://github.com/CheshireCaat/BASRemote.NET/blob/42b57cfcabea6dec0c67e181590615cc63e57df9/BASRemote/BasRemoteClient.cs#L113-L130

The process starts and connects to the socket as usual. All processes associated with the final step - an authorization error, successful authorization, or timeout cancellation are associated only with this line:
https://github.com/CheshireCaat/BASRemote.NET/blob/42b57cfcabea6dec0c67e181590615cc63e57df9/BASRemote/BasRemoteClient.cs#L127

In my previous post, I had in mind this:

Suppose you specify a timeout of 60 seconds. In this case, the start of the process took 15. Then, while waiting for the last step, only 45 seconds will remain for waiting. After that, the task will be canceled. I.e. it affects only on final step, but the time to wait can be lower than you specify in function call. 

Perhaps we did not understand each other, but this is so as to clarify. In general, if necessary, I can do the timeout processing not for the whole Start function, as it is now, but for the last step only.

**Comment by bablosoft** [comment]
Ok, can you make it default to 60 sec, so user don't have to modify code?

**Comment by CheshireCaat** [comment]
Ok, I'll do it a bit later

**Comment by bablosoft** [comment]
Ok, thanks

**Comment by CheshireCaat** [comment]
Think it solved in this commit https://github.com/CheshireCaat/BASRemote.NET/commit/38a35d1738dc51526a96bd229c956bee2e527a77
If i'm right, close the issue, please.

**Comment by bablosoft** [comment]
Checked, that message BAS from during authentication throws exception with correct text. Didn't check timeout while waiting for message. Anyway, second case must be rare.
